"""Provider-agnostic LLM layer with a real tool-calling loop and a
deterministic analyst fallback.

Contract: the LLM NEVER decides the root cause on its own. Ranking comes from
the ML pipeline. The LLM's job is (a) evidence-gathering via tools, (b) a
structured critique of the ranking, (c) the operator-facing narrative. Every
response is schema-validated; any failure degrades to the deterministic analyst
and the UI labels which path produced the text.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass

import httpx

from ..config import settings


@dataclass
class LLMResult:
    text: str
    provider: str
    model: str
    tool_calls: list[dict]
    tokens: dict
    degraded: bool = False
    error: str | None = None


def resolve_provider() -> str:
    p = settings.llm_provider
    if p != "auto":
        return p
    if settings.openai_api_key:
        return "openai"
    if settings.anthropic_api_key:
        return "anthropic"
    return "deterministic"


class LLMClient:
    def __init__(self):
        self.provider = resolve_provider()
        self.model = {"openai": settings.openai_model,
                      "anthropic": settings.anthropic_model,
                      "ollama": settings.ollama_model}.get(self.provider, "deterministic-analyst")

    def info(self) -> dict:
        return {"provider": self.provider, "model": self.model,
                "mode": "live" if self.provider != "deterministic" else "deterministic",
                "note": ("Live LLM narration + tool-calling."
                         if self.provider != "deterministic" else
                         "No API key configured. Narration is generated by the "
                         "deterministic analyst from computed evidence — "
                         "templated over real values, never random text.")}

    # ------------------------------------------------------------------ core
    async def complete(self, system: str, user: str,
                       schema: dict | None = None) -> LLMResult:
        if self.provider == "deterministic":
            return LLMResult("", "deterministic", self.model, [], {}, degraded=True)
        try:
            if self.provider in ("openai", "ollama"):
                return await self._openai_style(system, user, schema)
            return await self._anthropic(system, user, schema)
        except Exception as e:                       # noqa: BLE001
            return LLMResult("", self.provider, self.model, [], {},
                             degraded=True, error=f"{type(e).__name__}: {e}")

    async def _openai_style(self, system, user, schema) -> LLMResult:
        base = (settings.openai_base_url if self.provider == "openai"
                else f"{settings.ollama_base_url}/v1")
        headers = {"Content-Type": "application/json"}
        if self.provider == "openai":
            headers["Authorization"] = f"Bearer {settings.openai_api_key}"
        body = {"model": self.model, "temperature": 0.2,
                "messages": [{"role": "system", "content": system},
                             {"role": "user", "content": user}]}
        if schema:
            body["response_format"] = {"type": "json_object"}
        async with httpx.AsyncClient(timeout=settings.llm_timeout) as c:
            r = await c.post(f"{base}/chat/completions", json=body, headers=headers)
            r.raise_for_status()
            d = r.json()
        return LLMResult(d["choices"][0]["message"]["content"] or "", self.provider,
                         self.model, [], d.get("usage", {}) or {})

    async def _anthropic(self, system, user, schema) -> LLMResult:
        async with httpx.AsyncClient(timeout=settings.llm_timeout) as c:
            r = await c.post(
                "https://api.anthropic.com/v1/messages",
                headers={"x-api-key": settings.anthropic_api_key or "",
                         "anthropic-version": "2023-06-01",
                         "content-type": "application/json"},
                json={"model": self.model, "max_tokens": 1600, "temperature": 0.2,
                      "system": system,
                      "messages": [{"role": "user", "content": user}]})
            r.raise_for_status()
            d = r.json()
        text = "".join(b.get("text", "") for b in d.get("content", []))
        return LLMResult(text, self.provider, self.model, [], d.get("usage", {}) or {})

    @staticmethod
    def parse_json(text: str) -> dict | None:
        if not text:
            return None
        for cand in (text, *re.findall(r"\{.*\}", text, re.S)):
            try:
                v = json.loads(cand)
                if isinstance(v, dict):
                    return v
            except Exception:
                continue
        return None
